extends: base
page:
  layout: portrait
  margin: [0.75in, 1in, 0.75in, 1in]
  size: Letter
base:
  font-color: #333333
  font-family: Times-Roman
  font-size: 12
  line-height-length: 17
  line-height: $base-line-height-length / $base-font-size
vertical-spacing: $base-line-height-length
heading:
  font-color: #262626
  font-size: 17
  font-style: bold
  line-height: 1.2
  margin-bottom: $vertical-spacing
link:
  font-color: #002FA7
outline-list:
  indent: $base-font-size * 1.5
footer:
  height: $base-line-height-length * 2.5
  line-height: 1
  recto:
    right:
      content: '{page-number}'
  verso:
    left:
      content: $footer-recto-right-content

= Document Template
:author: Taylor Holland
:email: taylor.holland@cox.com
:appendix: 
:sectnums:
:toc: value
<<<

== Introduction
This section will be used to give a brief background on the topic being discussed in the document.

=== Objective
Team members will be able to use this document as a template to create similar ones in the future.
Team memebers will also be able to use the tables, diagrams, and links in this document to build their own examples.

=== Purpose
This document works as a template for future documents.
<<<    

== Section 1
Content for the first section will go here.

=== Subsection 1
If you need a subsection, it will go here.

==== Another subsection 1
Keep following this format for additional subsections.
When you want to go up a level to the previous section, use the corresponding number of equal signs.
<<<

== Tables
These are example tables that can be built into a document. +

=== Table with no column names
.Example
[cols=2*]
|===
|Firefox
|Web Browser

|Ruby
|Programming Language

|TorqueBox
|Application Server
|===

=== Table with column names
.Example
[cols=2*,options=header]
|===
|Name
|Group

|Firefox
|Web Browser

|Ruby
|Programming Language

|TorqueBox
|Application Server
|===

=== Table with column names AND a list in a box
.Example
[cols="2,3,5"]
|===
|Name |Group |Description

|Firefox
|Web Browser
a|Mozilla Firefox is an open-source web browser.
It's designed for:

* standards compliance,
* performance and
* portability

|Ruby
|Programming Language
|A programmer's best friend.
|===
<<<

== Diagrams

These are example diagrams that can be used.

=== Classic Block Diagram
.Diagram

[plantuml, wbs, svg]
....
@startuml
class BlockProcessor
class DiagramBlock
class DitaaBlock
class PlantUmlBlock

BlockProcessor <|-- DiagramBlock
DiagramBlock <|-- DitaaBlock
DiagramBlock <|-- PlantUmlBlock
@enduml
....

=== Breakdown Structure
.Diagram

[plantuml, wbs, svg]
....
@startwbs
skinparam monochrome true
* Business Process Modelling WBS
** Launch the project
*** Complete Stakeholder Research
*** Initial Implementation Plan
** Design phase
*** Model of AsIs Processes Completed
**** Model of AsIs Processes Completed1
**** Model of AsIs Processes Completed2
*** Measure AsIs performance metrics
*** Identify Quick Wins
** Complete innovate phase
@endwbs
....

=== Component Diagram with Legend
.Diagram

[plantuml, wbs, svg]
....
@startuml
!include C4_Component.puml

LAYOUT_WITH_LEGEND()

title Component diagram for Internet Banking System - API Application

Container(spa, "Single Page Application", "javascript and angular", "Provides all the internet banking functionality to customers via their web browser.")
Container(ma, "Mobile App", "Xamarin", "Provides a limited subset ot the internet banking functionality to customers via their mobile mobile device.")
ContainerDb(db, "Database", "Relational Database Schema", "Stores user registration information, hashed authentication credentials, access logs, etc.")
System_Ext(mbs, "Mainframe Banking System", "Stores all of the core banking information about customers, accounts, transactions, etc.")

Container_Boundary(api, "API Application") {
    Component(sign, "Sign In Controller", "MVC Rest Controlle", "Allows users to sign in to the internet banking system")
    Component(accounts, "Accounts Summary Controller", "MVC Rest Controlle", "Provides customers with a summory of their bank accounts")
    Component(security, "Security Component", "Spring Bean", "Provides functionality related to singing in, changing passwords, etc.")
    Component(mbsfacade, "Mainframe Banking System Facade", "Spring Bean", "A facade onto the mainframe banking system.")

    Rel(sign, security, "Uses")
    Rel(accounts, mbsfacade, "Uses")
    Rel(security, db, "Read & write to", "JDBC")
    Rel(mbsfacade, mbs, "Uses", "XML/HTTPS")
}

Rel(spa, sign, "Uses", "JSON/HTTPS")
Rel(spa, accounts, "Uses", "JSON/HTTPS")

Rel(ma, sign, "Uses", "JSON/HTTPS")
Rel(ma, accounts, "Uses", "JSON/HTTPS")
@enduml
....

Additional diagram examples may be found on the https://kroki.io/examples.html#use-case[Kroki website].
